### ISSUE TITLE
Returning null

### ISSUE THREAD

**Issue by 16isaac89** [kingflamez/laravelrave#103]
I am trying to do a transfer using laravel 8, php8.1, ravel4.2 but it keeps returning null every time
   $data = [
                "account_bank" => "MPS",
                "account_number" => "256781234567",
                "amount" => $requested,
                "narration" => $partner->name." "." Wallet withdrawal.",
                "currency" => "UGX",
                "reference" => $reference,
                "beneficiary_name" => $partner->name,
                'redirect_url' => route('callback.payout'),
              ];
              
              $transfer = Flutterwave::transfers()->initiate($data);
the keys are defined in the env under:
FLW_PUBLIC_KEY=
FLW_SECRET_KEY=

FLW_SECRET_HASH=

**Comment by ShoaibZhaid** [comment]
i am also face same issue like that

**Comment by 16isaac89** [comment]
Issue has been fixed by whitelisting my app's ipaddress
