### ISSUE TITLE
Unable to install on system running php 8.2

### ISSUE THREAD

**Issue by LL-Etiane** [kingflamez/laravelrave#105]
When trying to install it, the following error is gotten
`- kingflamez/laravelrave[1.0.0, ..., 1.0.1] require php ^5.4.0|^7.0 -> your php version (8.2.0) does not satisfy that requirement.
    - kingflamez/laravelrave[1.0.2, ..., 1.1.3] require php ^5.6.0|^7.0 -> your php version (8.2.0) does not satisfy that requirement.
    - kingflamez/laravelrave[v1.1.4, 2.0.0, 3.0.0, v4.0.0] require php ^5.6.0|^7.2 -> your php version (8.2.0) does not satisfy that requirement.`

**Comment by Raicon47** [comment]
same issue...needs to update the package

**Comment by HopekellDev** [comment]
Please help provide support for the latest Laravel....

**Comment by Irfan-Majid** [comment]
we are waiting
