### ISSUE TITLE
Invalid config file format

### ISSUE THREAD

**Issue by odeke** [kingflamez/laravelrave#14]
app/config/rave.php

>     /**

>      * Public Key: Your Rave publicKey. Sign up on https://rave.flutterwave.com/ to get one from your settings page
>      *
>      */
>     'publicKey' => env('RAVE_PUBLIC_KEY'),
>     /**
>      * Secret Key: Your Rave secretKey. Sign up on https://rave.flutterwave.com/ to get one from your settings page
>      *
>      */
>     'secretKey' => env('RAVE_SECRET_KEY'),

But it should be, 

> return [
> 
>     /**
>      * Public Key: Your Rave publicKey. Sign up on https://rave.flutterwave.com/ to get one from your settings page
>      *
>      */
>     'publicKey' => env('RAVE_PUBLIC_KEY', 'FLWPUBK-xxxxxxxxx-X'),
> 
>     /**
>      * Secret Key: Your Rave secretKey. Sign up on https://rave.flutterwave.com/ to get one from your settings page
>      *
>      */
>     'secretKey' => env('RAVE_SECRET_KEY','FLWSECK-xxxxxxx-X'),
>
Otherwise you will have an undefined public key and secret.

**Comment by kingflamez** [comment]
The keys are compulsory
