### ISSUE TITLE
Issue with Split Payment (SubAccounts)

### ISSUE THREAD

**Issue by Tarhex** [kingflamez/laravelrave#16]
I have issues with split payments via API. I have been able to create sub-accounts via successfully but payments does not appear under the sub-account in my test dashboard. I have included all necessary parameters and they are served successfully to the Rave Endpoint and when payment is successful, the sub-account does not receive it's suppose split of the payment.

Thanks

**Comment by kingflamez** [comment]
Sorry about this, should work now
