### ISSUE TITLE
Support for Laravel 6.9

### ISSUE THREAD

**Issue by AndreKendeck** [kingflamez/laravelrave#19]

**Comment by nanichang** [comment]
Is support for laravel 6.* coming anytime soon?

**Comment by AndreKendeck** [comment]
Yeah I am also wondering cause it would be beneficial for the future.

**Comment by nanichang** [comment]
Still no support for Laravel 6.* or a work around?

**Comment by AndreKendeck** [comment]
I think at this point its better to FORK your own and configure it from there cause its hard outchea 😂

**Comment by kingflamez** [comment]
Sorry guys, at this time I don't do PHP anymore and it's been a year plus. I will appreciate if anyone is willing to contribute
