### ISSUE TITLE
Payment Issue

### ISSUE THREAD

**Issue by ionware** [kingflamez/laravelrave#22]
I suppose this should be a critical bug or something in the newly released version **(v1.1.4)**. 

 ## Description
- When the payment is initialized, it is no more redirecting to rave payment gateway like the previous version, it only opened up the gateway within the app (like an inline solution).

- Right after the payment is completed successfully, it bounced back again, asking user to make the same payment, then the suddenly redirects to the provided callback.

- The callback now is called wrongly, the callback is being called with a GET request, and wrong query parameters.

All of this issue arise only in the v1.1.4

**Comment by wallacemyem** [comment]
I believe if you provide your redirect URL in `YourController` it will redirect after the successful payment. I can be wrong but that was my approach.

**Comment by kingflamez** [comment]
Thanks I'll take a look

**Comment by kingflamez** [comment]
Fixed
