### ISSUE TITLE
Logs User out after routing to /rave/callback

### ISSUE THREAD

**Issue by Stancobridge** [kingflamez/laravelrave#28]
I noticed that once my app redirects to /rave/callback a route that doesn't require auth, but once rave makes a request to that page it logs the current user out.

`Route::post('/rave/callback', 'Api\RaveController@callback')->name('callback');`
In my controller I have
`
        $resp = Rave::verifyTransaction(request()->txref);
        $chargeResponsecode = $resp->data->chargecode;
        $chargeAmount = $resp->data->amount;
        $chargeCurrency = $resp->data->currency;
        $respData = $resp->data;
    
        
        $deposit = Deposit::where(
            'txref', '=', $resp->data->txref
        )->first();

        $currency = "NGN";
        if (($chargeResponsecode == "00" || $chargeResponsecode == "0") && ($chargeAmount == $deposit->amount)  && ($chargeCurrency == $currency) && $deposit) {
        // transaction was successful...
            $deposit->status = true;
            $deposit->chargecode = $respData->chargecode;
            $deposit->chargedamount = $respData->chargedamount;
            $deposit->acctmessage = $respData->acctmessage;
            $deposit->user->account_balance += $deposit->amount;
            $deposit->user->save();
            $deposit->save();
        
            
            return redirect('/account/deposit/success?txref='.$respData->txref);
        
        } else {
            //Don't Give Value and return to the Failure page
        
            return redirect('/failed');
        }
   
      }`

**Comment by kingflamez** [comment]
Please retry with the new release
