### ISSUE TITLE
issue getting the card details

### ISSUE THREAD

**Issue by odion-cloud** [kingflamez/laravelrave#34]
when i use dd()  for the call back return i could not get card details , any help on how to get the card details

**Comment by chygoz2** [comment]
> when i use dd() for the call back return i could not get card details , any help on how to get the card details

Why do you want the card details?

**Comment by odion-cloud** [comment]
to sa

> > when i use dd() for the call back return i could not get card details , any help on how to get the card details
> 
> Why do you want the card details?

to save users card details for any other transaction

**Comment by ladaposamuel** [comment]
You cannot get/save a user's card details, but you can get the customer's token to always charge them again.

https://developer.flutterwave.com/reference#charge-with-token-1
