### ISSUE TITLE
Payment Issue after card enter the (Processing payment. Do not close modal.) keep loading without any redirect

### ISSUE THREAD

**Issue by odion-cloud** [kingflamez/laravelrave#35]
please i need help artisans, after inserting test card and pass  Otp verication the rave spinner keep spining withtout any redirect 
 this is my controller code!

  /**
   * Initialize Rave payment process
   * @return void
   */
  public function initialize(Request $request)
  {
    
        Rave::initialize(route('callback'));
       
  }

  /**
   * Obtain Rave callback information
   * @return void
   */
  public function callback(Request $request)
  {

    $obj = json_decode($request->resp,true);

    $txRef = $obj['data']['transactionobject']['txRef'];
    $data = Rave::verifyTransaction($txRef);
    if ($txRef) {

    $user = User::first();
    $user->deposit(['data']['transactionobject']['amount']);
    $user->activate = 1;
    $user->percentage = '40%';
    $user->update();
     redirect()->route('user')->with('success', 'you Acount is activated enjoy Saving with Buhatty!');
    }
   else {
     redirect()->route('savings')->with('error', 'Transaction Failed No Reference');
    }

}

**Comment by ladaposamuel** [comment]
did you switch to test mode?

**Comment by odion-cloud** [comment]
> did you switch to test mode?

yes i did

**Comment by odion-cloud** [comment]
> did you switch to test mode?

nothing change

**Comment by ladaposamuel** [comment]
Try the following
- clear cookies or cache
- turn of adblockers
- try to set to test mode again
- ensure your webhook configs are set.

**Comment by kingflamez** [comment]
Fixed
