### ISSUE TITLE
Invalid public key passed

### ISSUE THREAD

**Issue by Dayveeys** [kingflamez/laravelrave#38]
I keep getting invalid public key passed

**Comment by redx1t** [comment]
Have you published the vendor file? 

`php artisan vendor:publish`

if yes, double check your api keys as offered on flutterwave portal as well as ensure the env is correctly set.

**Comment by lordfj** [comment]
Any solution to this yet? 

I have done `php artisan vendor:publish`

I have cross checked my API keys and they are correct.

When I searched for the issue, most answers were about people mistakenly using staging API keys when they are live or using live keys in staging mode, but I've cross checked that too.

I'm in staging and my API keys are from sandbox. Still keep getting the same error. 

I've cleared cache multiple times, still no solution.

**Comment by kingflamez** [comment]
Please test it with the new release
