### ISSUE TITLE
Class 'Unirest\\Request' not found

### ISSUE THREAD

**Issue by kayleb01** [kingflamez/laravelrave#43]
Tried using this package to implement payment for a laravel app i'm building and upon sending request, the error i got..
![Screenshot from 2021-03-21 13-01-40](https://user-images.githubusercontent.com/52761552/111905924-0d468000-8a46-11eb-823d-4e92928e5b3c.png)

**Comment by kingflamez** [comment]
Sorry about this, fixed

**Comment by kayleb01** [comment]
Thanks...
