### ISSUE TITLE
Call to undefined method KingFlamez\Rave\Rave::initialize()

### ISSUE THREAD

**Issue by PromiseShedrach** [kingflamez/laravelrave#46]
hello,

im using laravel 8 and i keep getting this error, pls can i get help with it

**Comment by kingflamez** [comment]
I'll check it out

**Comment by kingflamez** [comment]
@PromiseShedrach please check the documentation, it's initializePayment not just initialize

**Comment by PromiseShedrach** [comment]
ok thank you, but initializePayment() is returning null
and so this `redirect($payment['link'])` is not redirecting

**Comment by kingflamez** [comment]
There is a new documentation, it's different from the old one, please check it out

**Comment by kingflamez** [comment]
@PromiseShedrach https://laravelrave.netlify.app/getting-started/payment-implementation.html#_1-setup-routes

**Comment by kingflamez** [comment]
Hi @PromiseShedrach can you link up with #47
