### ISSUE TITLE
Rave.php #53: Call to undefined method Monolog\Logger::useDailyFiles()

### ISSUE THREAD

**Issue by anasbakro** [kingflamez/laravelrave#5]
After installing the package, when I try 'php artisan ide-helper:generate ' command it throws an exception:
![screenshot_1](https://user-images.githubusercontent.com/3681552/39511101-e1f0c8ba-4df4-11e8-9b8a-4df941f77e26.png)

**Comment by anasbakro** [comment]
I'm using Laravel 5.6.

**Comment by kingflamez** [comment]
I will check it out

**Comment by anasbakro** [comment]
Thanks, but did you look into it because it is really annoying commenting this line in vendor after each composer install command.

**Comment by kingflamez** [comment]
Fixed
